#ifndef SCANCODE_HPP
#define SCANCODE_HPP

/*
* The values in this enumeration are based on the USB usage page standard :
* http://www.usb.org/developers/hidpage/Hut1_12v2.pdf chapter 10
*/

namespace Ryujin
{
	enum RyujinScanCode
	{
		RYUJIN_SCANCODE_UNKNOWN = 0,

		RYUJIN_SCANCODE_A = 4,
		RYUJIN_SCANCODE_B = 5,
		RYUJIN_SCANCODE_C = 6,
		RYUJIN_SCANCODE_D = 7,
		RYUJIN_SCANCODE_E = 8,
		RYUJIN_SCANCODE_F = 9,
		RYUJIN_SCANCODE_G = 10,
		RYUJIN_SCANCODE_H = 11,
		RYUJIN_SCANCODE_I = 12,
		RYUJIN_SCANCODE_J = 13,
		RYUJIN_SCANCODE_K = 14,
		RYUJIN_SCANCODE_L = 15,
		RYUJIN_SCANCODE_M = 16,
		RYUJIN_SCANCODE_N = 17,
		RYUJIN_SCANCODE_O = 18,
		RYUJIN_SCANCODE_P = 19,
		RYUJIN_SCANCODE_Q = 20,
		RYUJIN_SCANCODE_R = 21,
		RYUJIN_SCANCODE_S = 22,
		RYUJIN_SCANCODE_T = 23,
		RYUJIN_SCANCODE_U = 24,
		RYUJIN_SCANCODE_V = 25,
		RYUJIN_SCANCODE_W = 26,
		RYUJIN_SCANCODE_X = 27,
		RYUJIN_SCANCODE_Y = 28,
		RYUJIN_SCANCODE_Z = 29,

		RYUJIN_SCANCODE_1 = 30,
		RYUJIN_SCANCODE_2 = 31,
		RYUJIN_SCANCODE_3 = 32,
		RYUJIN_SCANCODE_4 = 33,
		RYUJIN_SCANCODE_5 = 34,
		RYUJIN_SCANCODE_6 = 35,
		RYUJIN_SCANCODE_7 = 36,
		RYUJIN_SCANCODE_8 = 37,
		RYUJIN_SCANCODE_9 = 38,
		RYUJIN_SCANCODE_0 = 39,

		RYUJIN_SCANCODE_RETURN = 40,
		RYUJIN_SCANCODE_ESCAPE = 41,
		RYUJIN_SCANCODE_BACKSPACE = 42,
		RYUJIN_SCANCODE_TAB = 43,
		RYUJIN_SCANCODE_SPACE = 44,

		RYUJIN_SCANCODE_MINUS = 45,
		RYUJIN_SCANCODE_EQUALS = 46,
		RYUJIN_SCANCODE_LEFTBRACKET = 47,
		RYUJIN_SCANCODE_RIGHTBRACKET = 48,
		RYUJIN_SCANCODE_BACKSLASH = 49, /**< Located at the lower left of the return
									 *   key on ISO keyboards and at the right end
									 *   of the QWERTY row on ANSI keyboards.
									 *   Produces REVERSE SOLIDUS (backslash) and
									 *   VERTICAL LINE in a US layout, REVERSE
									 *   SOLIDUS and VERTICAL LINE in a UK Mac
									 *   layout, NUMBER SIGN and TILDE in a UK
									 *   Windows layout, DOLLAR SIGN and POUND SIGN
									 *   in a Swiss German layout, NUMBER SIGN and
									 *   APOSTROPHE in a German layout, GRAVE
									 *   ACCENT and POUND SIGN in a French Mac
									 *   layout, and ASTERISK and MICRO SIGN in a
									 *   French Windows layout.
									 */
		RYUJIN_SCANCODE_NONUSHASH = 50,
		RYUJIN_SCANCODE_SEMICOLON = 51,
		RYUJIN_SCANCODE_APOSTROPHE = 52,
		RYUJIN_SCANCODE_GRAVE = 53, /**< Located in the top left corner (on both ANSI
								 *   and ISO keyboards). Produces GRAVE ACCENT and
								 *   TILDE in a US Windows layout and in US and UK
								 *   Mac layouts on ANSI keyboards, GRAVE ACCENT
								 *   and NOT SIGN in a UK Windows layout, SECTION
								 *   SIGN and PLUS-MINUS SIGN in US and UK Mac
								 *   layouts on ISO keyboards, SECTION SIGN and
								 *   DEGREE SIGN in a Swiss German layout (Mac:
								 *   only on ISO keyboards), CIRCUMFLEX ACCENT and
								 *   DEGREE SIGN in a German layout (Mac: only on
								 *   ISO keyboards), SUPERSCRIPT TWO and TILDE in a
								 *   French Windows layout, COMMERCIAL AT and
								 *   NUMBER SIGN in a French Mac layout on ISO
								 *   keyboards, and LESS-THAN SIGN and GREATER-THAN
								 *   SIGN in a Swiss German, German, or French Mac
								 *   layout on ANSI keyboards.
								 */
		RYUJIN_SCANCODE_COMMA = 54,
		RYUJIN_SCANCODE_PERIOD = 55,
		RYUJIN_SCANCODE_SLASH = 56,

		RYUJIN_SCANCODE_CAPSLOCK = 57,

		RYUJIN_SCANCODE_F1 = 58,
		RYUJIN_SCANCODE_F2 = 59,
		RYUJIN_SCANCODE_F3 = 60,
		RYUJIN_SCANCODE_F4 = 61,
		RYUJIN_SCANCODE_F5 = 62,
		RYUJIN_SCANCODE_F6 = 63,
		RYUJIN_SCANCODE_F7 = 64,
		RYUJIN_SCANCODE_F8 = 65,
		RYUJIN_SCANCODE_F9 = 66,
		RYUJIN_SCANCODE_F10 = 67,
		RYUJIN_SCANCODE_F11 = 68,
		RYUJIN_SCANCODE_F12 = 69,

		RYUJIN_SCANCODE_PRINTSCREEN = 70,
		RYUJIN_SCANCODE_SCROLLLOCK = 71,
		RYUJIN_SCANCODE_PAUSE = 72,
		RYUJIN_SCANCODE_INSERT = 73, /**< insert on PC, help on some Mac keyboards (but
								  does send code 73, not 117) */
		RYUJIN_SCANCODE_HOME = 74,
		RYUJIN_SCANCODE_PAGEUP = 75,
		RYUJIN_SCANCODE_DELETE = 76,
		RYUJIN_SCANCODE_END = 77,
		RYUJIN_SCANCODE_PAGEDOWN = 78,
		RYUJIN_SCANCODE_RIGHT = 79,
		RYUJIN_SCANCODE_LEFT = 80,
		RYUJIN_SCANCODE_DOWN = 81,
		RYUJIN_SCANCODE_UP = 82,

		RYUJIN_SCANCODE_NUMLOCKCLEAR = 83, /**< num lock on PC, clear on Mac keyboards
										*/
		RYUJIN_SCANCODE_KP_DIVIDE = 84,
		RYUJIN_SCANCODE_KP_MULTIPLY = 85,
		RYUJIN_SCANCODE_KP_MINUS = 86,
		RYUJIN_SCANCODE_KP_PLUS = 87,
		RYUJIN_SCANCODE_KP_ENTER = 88,
		RYUJIN_SCANCODE_KP_1 = 89,
		RYUJIN_SCANCODE_KP_2 = 90,
		RYUJIN_SCANCODE_KP_3 = 91,
		RYUJIN_SCANCODE_KP_4 = 92,
		RYUJIN_SCANCODE_KP_5 = 93,
		RYUJIN_SCANCODE_KP_6 = 94,
		RYUJIN_SCANCODE_KP_7 = 95,
		RYUJIN_SCANCODE_KP_8 = 96,
		RYUJIN_SCANCODE_KP_9 = 97,
		RYUJIN_SCANCODE_KP_0 = 98,
		RYUJIN_SCANCODE_KP_PERIOD = 99,

		RYUJIN_SCANCODE_NONUSBACKSLASH = 100, /**< This is the additional key that ISO
										   *   keyboards have over ANSI ones,
										   *   located between left shift and Y.
										   *   Produces GRAVE ACCENT and TILDE in a
										   *   US or UK Mac layout, REVERSE SOLIDUS
										   *   (backslash) and VERTICAL LINE in a
										   *   US or UK Windows layout, and
										   *   LESS-THAN SIGN and GREATER-THAN SIGN
										   *   in a Swiss German, German, or French
										   *   layout. */
		RYUJIN_SCANCODE_APPLICATION = 101, /**< windows contextual menu, compose */
		RYUJIN_SCANCODE_POWER = 102, /**< The USB document says this is a status flag,
								  *   not a physical key - but some Mac keyboards
								  *   do have a power key. */
		RYUJIN_SCANCODE_KP_EQUALS = 103,
		RYUJIN_SCANCODE_F13 = 104,
		RYUJIN_SCANCODE_F14 = 105,
		RYUJIN_SCANCODE_F15 = 106,
		RYUJIN_SCANCODE_F16 = 107,
		RYUJIN_SCANCODE_F17 = 108,
		RYUJIN_SCANCODE_F18 = 109,
		RYUJIN_SCANCODE_F19 = 110,
		RYUJIN_SCANCODE_F20 = 111,
		RYUJIN_SCANCODE_F21 = 112,
		RYUJIN_SCANCODE_F22 = 113,
		RYUJIN_SCANCODE_F23 = 114,
		RYUJIN_SCANCODE_F24 = 115,
		RYUJIN_SCANCODE_EXECUTE = 116,
		RYUJIN_SCANCODE_HELP = 117,
		RYUJIN_SCANCODE_MENU = 118,
		RYUJIN_SCANCODE_SELECT = 119,
		RYUJIN_SCANCODE_STOP = 120,
		RYUJIN_SCANCODE_AGAIN = 121,   /**< redo */
		RYUJIN_SCANCODE_UNDO = 122,
		RYUJIN_SCANCODE_CUT = 123,
		RYUJIN_SCANCODE_COPY = 124,
		RYUJIN_SCANCODE_PASTE = 125,
		RYUJIN_SCANCODE_FIND = 126,
		RYUJIN_SCANCODE_MUTE = 127,
		RYUJIN_SCANCODE_VOLUMEUP = 128,
		RYUJIN_SCANCODE_VOLUMEDOWN = 129,
		RYUJIN_SCANCODE_KP_COMMA = 133,
		RYUJIN_SCANCODE_KP_EQUALSAS400 = 134,

		RYUJIN_SCANCODE_INTERNATIONAL1 = 135, /**< used on Asian keyboards, see
										   footnotes in USB doc */
		RYUJIN_SCANCODE_INTERNATIONAL2 = 136,
		RYUJIN_SCANCODE_INTERNATIONAL3 = 137, /**< Yen */
		RYUJIN_SCANCODE_INTERNATIONAL4 = 138,
		RYUJIN_SCANCODE_INTERNATIONAL5 = 139,
		RYUJIN_SCANCODE_INTERNATIONAL6 = 140,
		RYUJIN_SCANCODE_INTERNATIONAL7 = 141,
		RYUJIN_SCANCODE_INTERNATIONAL8 = 142,
		RYUJIN_SCANCODE_INTERNATIONAL9 = 143,
		RYUJIN_SCANCODE_LANG1 = 144, /**< Hangul/English toggle */
		RYUJIN_SCANCODE_LANG2 = 145, /**< Hanja conversion */
		RYUJIN_SCANCODE_LANG3 = 146, /**< Katakana */
		RYUJIN_SCANCODE_LANG4 = 147, /**< Hiragana */
		RYUJIN_SCANCODE_LANG5 = 148, /**< Zenkaku/Hankaku */
		RYUJIN_SCANCODE_LANG6 = 149, /**< reserved */
		RYUJIN_SCANCODE_LANG7 = 150, /**< reserved */
		RYUJIN_SCANCODE_LANG8 = 151, /**< reserved */
		RYUJIN_SCANCODE_LANG9 = 152, /**< reserved */

		RYUJIN_SCANCODE_ALTERASE = 153, /**< Erase-Eaze */
		RYUJIN_SCANCODE_SYSREQ = 154,
		RYUJIN_SCANCODE_CANCEL = 155,
		RYUJIN_SCANCODE_CLEAR = 156,
		RYUJIN_SCANCODE_PRIOR = 157,
		RYUJIN_SCANCODE_RETURN2 = 158,
		RYUJIN_SCANCODE_SEPARATOR = 159,
		RYUJIN_SCANCODE_OUT = 160,
		RYUJIN_SCANCODE_OPER = 161,
		RYUJIN_SCANCODE_CLEARAGAIN = 162,
		RYUJIN_SCANCODE_CRSEL = 163,
		RYUJIN_SCANCODE_EXSEL = 164,

		RYUJIN_SCANCODE_KP_00 = 176,
		RYUJIN_SCANCODE_KP_000 = 177,
		RYUJIN_SCANCODE_THOUSANDSSEPARATOR = 178,
		RYUJIN_SCANCODE_DECIMALSEPARATOR = 179,
		RYUJIN_SCANCODE_CURRENCYUNIT = 180,
		RYUJIN_SCANCODE_CURRENCYSUBUNIT = 181,
		RYUJIN_SCANCODE_KP_LEFTPAREN = 182,
		RYUJIN_SCANCODE_KP_RIGHTPAREN = 183,
		RYUJIN_SCANCODE_KP_LEFTBRACE = 184,
		RYUJIN_SCANCODE_KP_RIGHTBRACE = 185,
		RYUJIN_SCANCODE_KP_TAB = 186,
		RYUJIN_SCANCODE_KP_BACKSPACE = 187,
		RYUJIN_SCANCODE_KP_A = 188,
		RYUJIN_SCANCODE_KP_B = 189,
		RYUJIN_SCANCODE_KP_C = 190,
		RYUJIN_SCANCODE_KP_D = 191,
		RYUJIN_SCANCODE_KP_E = 192,
		RYUJIN_SCANCODE_KP_F = 193,
		RYUJIN_SCANCODE_KP_XOR = 194,
		RYUJIN_SCANCODE_KP_POWER = 195,
		RYUJIN_SCANCODE_KP_PERCENT = 196,
		RYUJIN_SCANCODE_KP_LESS = 197,
		RYUJIN_SCANCODE_KP_GREATER = 198,
		RYUJIN_SCANCODE_KP_AMPERSAND = 199,
		RYUJIN_SCANCODE_KP_DBLAMPERSAND = 200,
		RYUJIN_SCANCODE_KP_VERTICALBAR = 201,
		RYUJIN_SCANCODE_KP_DBLVERTICALBAR = 202,
		RYUJIN_SCANCODE_KP_COLON = 203,
		RYUJIN_SCANCODE_KP_HASH = 204,
		RYUJIN_SCANCODE_KP_SPACE = 205,
		RYUJIN_SCANCODE_KP_AT = 206,
		RYUJIN_SCANCODE_KP_EXCLAM = 207,
		RYUJIN_SCANCODE_KP_MEMSTORE = 208,
		RYUJIN_SCANCODE_KP_MEMRECALL = 209,
		RYUJIN_SCANCODE_KP_MEMCLEAR = 210,
		RYUJIN_SCANCODE_KP_MEMADD = 211,
		RYUJIN_SCANCODE_KP_MEMSUBTRACT = 212,
		RYUJIN_SCANCODE_KP_MEMMULTIPLY = 213,
		RYUJIN_SCANCODE_KP_MEMDIVIDE = 214,
		RYUJIN_SCANCODE_KP_PLUSMINUS = 215,
		RYUJIN_SCANCODE_KP_CLEAR = 216,
		RYUJIN_SCANCODE_KP_CLEARENTRY = 217,
		RYUJIN_SCANCODE_KP_BINARY = 218,
		RYUJIN_SCANCODE_KP_OCTAL = 219,
		RYUJIN_SCANCODE_KP_DECIMAL = 220,
		RYUJIN_SCANCODE_KP_HEXADECIMAL = 221,

		RYUJIN_SCANCODE_LCTRL = 224,
		RYUJIN_SCANCODE_LSHIFT = 225,
		RYUJIN_SCANCODE_LALT = 226, /**< alt, option */
		RYUJIN_SCANCODE_LGUI = 227, /**< windows, command (apple), meta */
		RYUJIN_SCANCODE_RCTRL = 228,
		RYUJIN_SCANCODE_RSHIFT = 229,
		RYUJIN_SCANCODE_RALT = 230, /**< alt gr, option */
		RYUJIN_SCANCODE_RGUI = 231, /**< windows, command (apple), meta */

		RYUJIN_SCANCODE_MODE = 257,  

		RYUJIN_SCANCODE_AUDIONEXT = 258,
		RYUJIN_SCANCODE_AUDIOPREV = 259,
		RYUJIN_SCANCODE_AUDIOSTOP = 260,
		RYUJIN_SCANCODE_AUDIOPLAY = 261,
		RYUJIN_SCANCODE_AUDIOMUTE = 262,
		RYUJIN_SCANCODE_MEDIASELECT = 263,
		RYUJIN_SCANCODE_WWW = 264,
		RYUJIN_SCANCODE_MAIL = 265,
		RYUJIN_SCANCODE_CALCULATOR = 266,
		RYUJIN_SCANCODE_COMPUTER = 267,
		RYUJIN_SCANCODE_AC_SEARCH = 268,
		RYUJIN_SCANCODE_AC_HOME = 269,
		RYUJIN_SCANCODE_AC_BACK = 270,
		RYUJIN_SCANCODE_AC_FORWARD = 271,
		RYUJIN_SCANCODE_AC_STOP = 272,
		RYUJIN_SCANCODE_AC_REFRESH = 273,
		RYUJIN_SCANCODE_AC_BOOKMARKS = 274,

		// keys for mac

		RYUJIN_SCANCODE_BRIGHTNESSDOWN = 275,
		RYUJIN_SCANCODE_BRIGHTNESSUP = 276,
		RYUJIN_SCANCODE_DISPLAYSWITCH = 277, 
		RYUJIN_SCANCODE_KBDILLUMTOGGLE = 278,
		RYUJIN_SCANCODE_KBDILLUMDOWN = 279,
		RYUJIN_SCANCODE_KBDILLUMUP = 280,
		RYUJIN_SCANCODE_EJECT = 281,
		RYUJIN_SCANCODE_SLEEP = 282,

		RYUJIN_SCANCODE_APP1 = 283,
		RYUJIN_SCANCODE_APP2 = 284,


		RYUJIN_NUM_SCANCODES = 512 
	};
}

#endif